### ISSUE TITLE
Msw is not working in Vitejs

### ISSUE THREAD

**Issue by YuesIt17** [mswjs/examples#119]
Hello!  I have a problem with Msw + vite. 

I have tried install latest version 2.4.2 and msw doesn't watch mock of api, i.e. i can not get into the handler of mock.
But I see in console "[MSW] Mocking enabled" and if you request the api again, then i get data from mock handler.

Example with bug
![vite_msw](https://github.com/user-attachments/assets/d261c2de-ab03-428b-ab72-611b14b764d5)

If you install for example "msw": "2.0.4", i don't have this problem
![vite_msw_2](https://github.com/user-attachments/assets/5a2c8604-27aa-4ba5-9281-bbc1e658208d)

**Comment by kettanaito** [comment]
Hi, @YuesIt17. 

Your first example shows that you forgot to await `worker.start()`. Once you do, all the requests will be intercepted and mocked as you expect. Here's the fix:

```diff
// main.jsx
-worker.start()
+await worker.start()
```
