### ISSUE TITLE
Running examples fails with missing module 'msw'

### ISSUE THREAD

**Issue by juhanakristian** [mswjs/examples#2]
## Description
Running examples locally fails because 'msw' module isn't installed.

## Steps to reproduce
```
git clone https://github.com/mswjs/examples
cd examples
yarn
cd examples/rest-react
yarn start
```

## Expected behaviour 
Example starts in browser

## Screenshots
![image](https://user-images.githubusercontent.com/544386/82484098-1a22dc00-9ae2-11ea-984f-8262707d00aa.png)

**Comment by kettanaito** [comment]
Hey, @juhanakristian. That's truly an unexpected behavior! Thanks for raising this.

I suppose I've got `msw` linked locally, so I never experienced that issue. Should be a matter of running `npx lerna add msw` on the root level of the repository. Let me know if you'd want to help me with that, I'd appreciate your involvement :) Thanks.

**Comment by juhanakristian** [comment]
Hi, @kettanaito. I figured you were linking `msw` locally but the README had no mention of linking or installing `msw`  so I decided to make an issue :) 

I'll make a PR :)
