### ISSUE TITLE
☝️ Question: Can I Spy on the server in my jest tests?

### ISSUE THREAD

**Issue by Norfeldt** [mswjs/examples#30]
Posted [the question on SO](https://stackoverflow.com/questions/63408769/spy-on-mock-service-worker-msw) and also dropping it here.

I'm starting to use the [msw (mock service worker)][1] after watching [this example][2] of how to use it for testing API calls in React applications.  

Is there any way that we can spy on the mock service worker?

For example:

```javascript
import React from 'react'
import { render, fireEvent, act, await } from '@testing-library/react'
import { rest } from 'msw'
import { setupServer } from 'msw/node'

import SearchBox from '.'

const fakeServer = setupServer(
  rest.get(
    'https://api.flickr.com/services/rest/?method=flickr.photos.search',
    (req, res, ctx) => res(ctx.status(200), ctx.json({ data: { photos: { photo: [] },},}))
  )
)

beforeAll(() => {fakeServer.listen()})
afterEach(() => {fakeServer.resetHandlers()})
afterAll(() => fakeServer.close())

test('it calls Flickr REST request when submitting search term', async () => {
  axios.get.mockImplementation(() => Promise.resolve({ data: {} }))
  const { getByLabelText } = render(<SearchBox />)
  const input = getByLabelText('Search Flickr')
  const submitButton = getByLabelText('Submit search')

  await act(async () => {
    await fireEvent.change(input, { target: { value: 'Finding Wally' } })
    await fireEvent.click(submitButton)
  })

  await wait()

  // TODO: assert that the fakeServer was called once and with the correct URL
})
```

The component to test looks like this:

```javascript
import React, { useState } from 'react'
import axios from 'axios'

import './index.css'

function SearchBox({ setPhotos }) {
  const [searchTerm, setSearchTerm] = useState('')

  const handleTyping = (event) => {
    event.preventDefault()
    setSearchTerm(event.currentTarget.value)
  }

  const handleSubmit = async (event) => {
    event.preventDefault()
    try {
      const restURL = `https://api.flickr.com/services/rest/?method=flickr.photos.search&api_key=${
        process.env.REACT_APP_API_KEY
      }&per_page=10&format=json&nojsoncallback=1'&text=${encodeURIComponent(
        searchTerm
      )}`
      const { data } = await axios.get(restURL)
      const fetchedPhotos = data.photos.photo
      setPhotos(fetchedPhotos)
    } catch (error) {
      console.error(error)
    }
  }

  return (
    <section style={styles.container}>
      <form action="" method="" style={styles.form}>
        <input
          aria-label="Search Flickr"
          style={styles.input}
          value={searchTerm}
          onChange={handleTyping}
        />
        <button
          aria-label="Submit search"
          style={styles.button}
          onClick={handleSubmit}
        >
          SEARCH
        </button>
      </form>
    </section>
  )
}
```

I have got a working test, but I feel it leans towards an implementation test since it uses a spy on the `setPhotos`

```javascript
test('it calls Flickr REST request when submitting search term', async () => {
  const fakeSetPhotos = jest.fn(() => {})
  const { getByLabelText } = render(<SearchBox setPhotos={fakeSetPhotos} />)
  const input = getByLabelText('Search Flickr')
  const submitButton = getByLabelText('Submit search')

  await act(async () => {
    await userEvent.type(input, 'Finding Walley')
    await userEvent.click(submitButton)
  })

  await wait()

  expect(fakeSetPhotos).toHaveBeenCalledWith([1, 2, 3])
})
```

  [1]: https://mswjs.io/
  [2]: https://github.com/leighhalliday/msw-example

**Comment by kettanaito** [comment]
Hey, @Norfeldt! Thanks for reaching out. I'll try to help you with this question below.

Let's start from the things that throw me off when reading the test.

## Omit query parameters in request handler URL

Including query parameters in the URL you want to mock does nothing, MSW strips query parameters off when comparing an actual request URL to the one you described in your request handlers.

```diff
-rest.get('https://api.flickr.com/services/rest/?method=flickr.photos.search')
+rest.get('https://api.flickr.com/services/rest')
```

If you wish to access that `method` query parameter, follow the [Query parameters](https://mswjs.io/docs/recipes/query-parameters) recipe. This can be useful if your response should differ based on the `method` value.

## Drop `.mockImplementation()`

The very philosophy behind MSW is that you stop mocking request issuing libraries and modules (like `axios`, `fetch`), and utilize MSW as the layer that guarantees your requests are performed correctly, are captured, and responded using given mocked data.

By calling `axios.get.mockImplementation(() => Promise.resolve({ data: {} }))` you silence the request, so the request never happens, and the `axios.get` call just returns the mocked Promise you specified. This gives you much less confidence that your app behaves correctly (for example, what if you constructed a wrong request url, or query parameter? Mocking `axios.get` would still return that hard-coded promise, resulting into a false positive test).

Instead, remove the `.mockImplementation()` altogether when using MSW.

```diff
-axios.get.mockImplementation(() => Promise.resolve({ data: {} }))
```

If you wish to respond to a request using mocked data, create a request handler (`rest.get`, `rest.post`, etc.) for that request and respond with `res()` in the response resolver. In your case you _already have_ that request handler, so there's no need to fake `axios.get`:

```js
rest.get('https://api.flickr.com/services/rest/?method=flickr.photos.search', ...)
```

---

Now getting to the original question, you shouldn't assert that `fakeServer` (`setupServer`) has been called, as that's a testing implementation detail. Imagine that fake server isn't even there, what would you expect from your component to do? Most often, HTTP requests result into UI updates, like rendering something new or updating existing nodes. Assert _that_. 

In case of your `SearchBox` component, it does an async request, but doesn't directly render anything based on the response. Instead, it passes the response data to the parent via `setPhotos` prop. To test this you need to emulate the "parent" context of some sort.

## Using plain callback

I usually approach such tests by creating an actual (not mocked) function that I pass as the value of such callback props.

```js
test('...', async () => {
  let photos

  // Create an actual callback function
  function setPhotos(data) {
    // which does an action of propagating given data
    // to the `photos` variable.
    photos = data
  }

  // Pass that callback function as a value to the `setPhotos` prop
  const { getByLabelText } = render(<SearchBox setPhotos={setPhotos} />)

  // Perform actions:
  // click buttons, submit forms

  // Assert result
  expect(photos).toEqual([1, 2, 3])
})
```

> In some cases you can also inline the value of such callbacks as `setPhotos={data => photos = data}`. Note that scoped mutations are perfectly fine.

We expect `setPhotos` function to be called after certain actions. Whenever it's called, it rewrites the `photos` data that we later perform assertions upon. 

Utilizing `jest.fn` or a regular function is a rather conceptual choice, there's no technical advantages/disadvantages here, but I find the straightforward the test is, the better. 

## Using a parent node

Perhaps a more realistic test would be to create a parent component that would render something in the response to `setPhotos` function being called.

```js
test('...', async () => {
  // Create a parent around `SearchBox`
  const Parent = () => {
    const [photos, setPhotos] = useState([])

    return (
      <div>
        <SearchBox setPhotos={setPhotos} />
        {photos.map((photo) => (
          // Render something based on the data received from `setPhotos`
          <img key={photo.id} alt={photo.title} src={photo.imageUrl} />
        ))}
      </div>
    )
  }

  render(<Parent />)

  // Do the same thing: perform actions
  // Assert that <img/> components are rendered correctly
})
```

I think this would be a **much better solution** in case of testing `SearchBox` behavior. It does take an isolation factor away, but you are testing `SearchBox` in conjuncture with another component, which is how it's being designed to be used. 

I hope this info helps. Let me know if there are any other questions in regards to this. Thanks!

**Comment by Norfeldt** [comment]
thank you so much for you time and help @kettanaito 👍

Can't stop thinking about what if I wish to test that it builds up the URL with correct query parameters?

----

the `axios.get.mockImplementation(() => Promise.resolve({ data: {} }))` was some left-over headache attempts that had sneak it's way into my code example. Sorry about that! I reached the same conclusion as you described but you described it very well and that will be useful to keep in mind.

**Comment by kettanaito** [comment]
> Can't stop thinking about what if I wish to test that it builds up the URL with correct query parameters?

You can reflect an invalid query parameter in the response resolver. If the query parameter is missing/invalid your real server would not produce the expected data, right? So with MSW your "real server" is your response resolver. Check the presence or value of that query parameter and raise an error in case that parameter is invalid.

```js
rest.get('https://api.flickr.com/services/rest/?method=flickr.photos.search', (req, res, ctx) => {
  const method = req.url.searchParams.get('method')

  if (!method) {
    // Consider a missing `method` query parameter as a bad request.
    return res(ctx.status(400))
  }

  // Depending on your logic, you can also check if the value of the `method`
  // parameter equals to "flickr.photos.search".

  return res(ctx.json({ successful: 'response' }))
})
```

Now, if your app misses the `method` query parameter in the request URL, it would get a 400 response, and shouldn't call the `setPhotos` callback in case of such unsuccessful response. 

Does this way of thinking makes sense to you?

**Comment by Norfeldt** [comment]
You are genius @kettanaito - thanks a lot!

**Comment by boltcoder** [comment]
There are plenty of reasons where a request could be just made in the background with no corresponding UI effect. 
For instance: Ping Scheduling, prefetching etc and to test our techniques we'd like to spy on the API getting called using MSW.

**Comment by kettanaito** [comment]
@boltcoder, then, by all means, do that:

```js
const requestSpy = jest.fn()
server.events.on('request:start', requestSpy)

it('your test', () => {
  expect(requestSpy).toHaveBeenCalledWith(expect.objectContaining({
    method: 'POST',
    url: new URL('https://analytics.service.com')
  }))
})
```

**Comment by jlgouwyapizr** [comment]
> There are plenty of reasons where a request could be just made in the background with no corresponding UI effect. For instance: Ping Scheduling, prefetching etc and to test our techniques we'd like to spy on the API getting called using MSW.

Indeed, I'm using MSW with Serverless Framework. So, back-end side.
And sometimes, we just want to ensure that we send right data in right endpoint. 

So I think you should update https://mswjs.io/docs/recipes/request-assertions , because after reading it, I was so confused.
I was wondering if I was testing in a bad way ... But I don't think so, and the answer of @boltcoder reassured me. 
 
 But thanks for your solution @kettanaito, it works well.

**Comment by kettanaito** [comment]
I think we generally should discourage request assertions. At least until we ship a standalone library that'd allow that in a way that makes it easier to do for consumers. Until then, I'd leave the docs as-is.

**Comment by cmacdonnacha** [comment]
> @boltcoder, then, by all means, do that:
> 
> ```js
> const requestSpy = jest.fn()
> server.events.on('request:start', requestSpy)
> 
> it('your test', () => {
>   expect(requestSpy).toHaveBeenCalledWith(expect.objectContaining({
>     method: 'POST',
>     url: new URL('https://analytics.service.com')
>   }))
> })
> ```


Hey @kettanaito 

Thanks for this. Do you know if there a way to supply a wildcard for the url? Something like

```javascript
it('your test', () => {
  expect(requestSpy).toHaveBeenCalledWith(expect.objectContaining({
    method: 'POST',
    url: new URL('*/users')
  }))
})
```

I just get this error: `TypeError: Invalid URL: */users`

**Comment by abhieshekumar** [comment]
@cmacdonnacha this should work.

```js
  it('your test', () => {
    expect(requestSpy).toHaveBeenCalledWith(expect.objectContaining({
      method: 'POST',
      url: expect.stringMatching(/users$/i),
    }))
  })
```

**Comment by cmacdonnacha** [comment]
Thanks @abhieshekumar 

As a side note for anyone coming to this discussion, there's some good info asserting requests [here](https://mswjs.io/docs/extensions/life-cycle-events#asserting-request-payload).

I have the `waitForRequest` as a utility function which I re-use across my tests for scenarios where I can't rely on asserting the UI (which is always my first choice).

**Comment by seunggs** [comment]
Using `waitForRequest` as per the docs seems to affect other tests in the same test file even though it's only used inside one test?

```
test('...', () => {
  ...
  const req = await waitForRequest('PUT', `${apiBaseUrl}/workflow-versions/:workflowVersionId`)
  expect(req.body.id).toBe(workflowVersion.id)
})
```

Above causes other tests to suddenly fail.

**Comment by kettanaito** [comment]
@cmacdonnacha, if you're using the `URL` class you have to construct a valid _absolute_ URL. Moreover, path wildcards won't have any effect here because it's a custom feature that URL knows nothing about (and neither does Jest to perform correct assertions). 

As others have rightfully pointed out, you're much better off using `expect.stringMatching`/`expect.stringContaining` asymmetric matchers to test the request URL. 

> Above causes other tests to suddenly fail.

@seunggs, that may be the case. I don't think we have a test suite for this particular behavior so I cannot prove that the documentation example will work correctly for all cases. Can you investigate how it affects other tests? This may be a good chance for us to improve this recipe.

**Comment by SMJ93** [comment]
@seunggs same here, did you manage to fix the issue? I've tried resetting the sever etc before each test but no luck

**Comment by cmacdonnacha** [comment]
> As a side note for anyone coming to this discussion, there's some good info asserting requests [here](https://mswjs.io/docs/extensions/life-cycle-events#asserting-request-payload).

Hey @kettanaito 

Just wondering if the `waitForRequest` example was purposely omitted from the 2.0 docs? I'm guessing yes since it did seem to be a bit flaky as similar to @seunggs, I found that it bled into tests that followed it.

**Comment by kettanaito** [comment]
@cmacdonnacha, that was not intentional. 2.0 examples were all written from scratch, and some functionality did not transfer directly from the previous examples. 

My default recommendation on request assertions [remains the same](https://mswjs.io/docs/best-practices/avoid-request-assertions). If you absolutely must do that, you can use the [Life-cycle API](https://mswjs.io/docs/api/life-cycle-events) to await whenever a `request:start`/`request:match` event is emitted. There should be nothing flaky about that.

**Comment by michaeltroya** [comment]
@kettanaito I am also seeing issues migrating over the `waitForRequest` function used in previous examples with v2.

going from 
```
function waitForRequest(method: string, url: string) {
  let requestId = ''

  return new Promise((resolve, reject) => {
    server.events.on('request:start', (req) => {
      const matchesMethod = req.method.toLowerCase() === method.toLowerCase()
      const matchesUrl = matchRequestUrl(req.url, url).matches

      if (matchesMethod && matchesUrl) {
        requestId = req.id
      }
    })

    server.events.on('request:match', (req) => {
      if (req.id === requestId) {
        resolve(req)
      }
    })

    server.events.on('request:unhandled', (req) => {
      if (req.id === requestId) {
        reject(
          new Error(`The ${req.method} ${req.url.href} request was unhandled.`),
        )
      }
    })
  })
}

```

to 

```
export const waitForRequest2 = (method: string, url: string) => {
  let reqId = ''

  return new Promise((resolve, reject) => {
    server.events.on('request:start', ({ request, requestId }) => {
      const matchesMethod =
        request.method.toLowerCase() === method.toLowerCase()
      const matchesUrl = request.url === url

      if (matchesMethod && matchesUrl) {
        reqId = requestId
      }
    })

    server.events.on('request:match', async ({ request, requestId }) => {
      const actualBody = await request.clone().json()

      if (requestId === reqId) {
        resolve(actualBody)
      }
    })

    server.events.on('request:unhandled', ({ request, requestId }) => {
      if (requestId === reqId) {
        reject(
          new Error(
            `The ${request.method} ${request.url} request was unhandled.`,
          ),
        )
      }
    })
  })
}
```

But now I'm seeing ` TypeError: unusable` when trying to parse the request body. Any ideas?

**Comment by kettanaito** [comment]
@michaeltroya, can you submit a reproduction repository for this, please? If the issue is fundamental, that code snippet is all you need to reproduce it. I can take a look at it then. Thanks.

**Comment by kettanaito** [comment]
That's unexpected though. If you clone the request in the life-cycle event listener, you must be able to read its body. That's the intended usage. To be safe, please make sure you are on the `msw@latest`. If that still persists, I'd love to see a reproduction repository. Or, if this is simple enough, a PR with a failing test will also be welcome!

**Comment by michaeltroya** [comment]
@kettanaito [here](https://github.com/michaeltroya/msw-waitForRequest-reproduction) is a repro of the issue. Please pnpm install and run pnpm test to test the `Component.test.tsx`. 

I do know that It's not a great practice to assert on request bodies in tests, and we should address it more holistically at my company. However, our primary goal currently is to upgrade to v2.

**Comment by michaeltroya** [comment]
@kettanaito would love to get your thoughts on this ^
