### ISSUE TITLE
Explicitally waiting for a network request

### ISSUE THREAD

**Issue by jmcrthrs** [mswjs/examples#43]
Hey there, I have been looking at the rest-react example and I notice that it does not explicitally wait for the network request to complete, which I think is typical in Cypress tests when using [cy.server & cy.route](https://docs.cypress.io/guides/guides/network-requests.html#Waiting)

I assume this is not required because when the Cypress test runner arrives on this line: https://github.com/mswjs/examples/blob/fa0eb64852f66b04b88efb6d343b17688f0a1bb6/examples/rest-react/e2e/Login.e2e.test.js#L12

it will wait for x seconds for that element to appear before failing. Because the msw handler defined here responds immediately, the React component will update, and Cypress will find the element.: https://github.com/mswjs/examples/blob/fa0eb64852f66b04b88efb6d343b17688f0a1bb6/examples/rest-react/src/mocks/handlers.js#L4

So I assume there is no need for us to explicitly wait in our tests for the network response?

I have forked this repo and added an assertion after the Login form is submitted, but it can never find the button.

https://github.com/jmcrthrs/examples

Perhaps you can clone the repo and run Cypress to see the behaviour, and if I am doing something wrong?

**Comment by timdeschryver** [comment]
> I have forked this repo and added an assertion after the Login form is submitted, but it can never find the button.

In the html the button is marked with `submit-button` as test id

```html
<button data-testid="submit-button" type="submit" className={loading ? "loading" : ""}>
          Submit
</button>
```

While the test is looking for 'button' as test id

```js
cy.get('[data-testid=button]').should('have.class', 'loading')
```

**Comment by jmcrthrs** [comment]
@timdeschryver Hey Tim, I think perhaps you have an old commit. Can you pull and try again?

The latest commit should be https://github.com/jmcrthrs/examples/commit/8bae3d824f368190c1773fa5b5fc440c99853449

**Comment by timdeschryver** [comment]
> So I assume there is no need for us to explicitly wait in our tests for the network response

Cypress has a retry ability, so even when the element isn't visible cypress will retry the query until it finds the element or times out. Because of this, I almost never wait for an HTTP request in my tests.

> I have forked this repo and added an assertion after the Login form is submitted, but it can never find the button.

This is because the MSW handler returns the result immediately so React doesn't render the loading indicator.
When you add a delay to the handler (like the one you commented out), it will work.

**Comment by kettanaito** [comment]
Hey, @jmcrthrs. Thanks for reaching out.

When it comes to testing intermediate state (i.e. loading), consider using the [`ctx.delay()`](https://mswjs.io/docs/api/context/delay) utility. It allows to set a response delay, thus making the loading state apparent in the UI. Here's how it'd look in your request handlers:

```js
rest.post('/login', (req, res, ctx) => {
  return res(ctx.delay(5000), ctx.json({ some: 'response' })
})
```

> The example above would delay the mocked response by 5000ms (5s), making it enough time for your testing framework to capture the loading state. 

You can also consider using it like `ctx.delay(Infinity)`, which would produce a mocked response that would never resolve. 

---

> So I assume there is no need for us to explicitly wait in our tests for the network response?

You're assuming correctly. Most of the test frameworks have a retry mechanism built-in, so the framework would run your assertion repeatedly for an N amount of time until it becomes true. This works beneficial when asserting UI derived from asynchronous operations like HTTP requests. 

Certain frameworks may provide you with an API to explicitly await HTTP requests, but you'd have to look such API up in their respective documentations. The usage of such API is up to you. 

Let us know if you have any other questions.
