### ISSUE TITLE
Just tried running this on my Mac M1 under Rosetta 2 - fails

### ISSUE THREAD

**Issue by azaeng04** [mswjs/examples#52]
I am literally just trying to start up the application

![Screenshot 2021-03-18 at 17 46 50](https://user-images.githubusercontent.com/13921692/111655600-7645b200-8812-11eb-9c89-f5d2975e5f96.png)

![Screenshot 2021-03-18 at 17 46 55](https://user-images.githubusercontent.com/13921692/111655609-780f7580-8812-11eb-9cc5-0a5c19659c15.png)

Some system info
```
arch: 'x64',
  platform: 'darwin',
  release: {
    name: 'node',
    lts: 'Fermium',
    sourceUrl: 'https://nodejs.org/download/release/v14.16.0/node-v14.16.0.tar.gz',
    headersUrl: 'https://nodejs.org/download/release/v14.16.0/node-v14.16.0-headers.tar.gz'
  },
```

**Comment by kettanaito** [comment]
Thanks for reporting this! The examples have been updated and I believe this issue is no longer present.
