### ISSUE TITLE
In mswjs/examples/rest-angular worker.start() is not awaited

### ISSUE THREAD

**Issue by divStar** [mswjs/examples#66]
Hello! First off: thank you for your amazing work! I really like the idea behind MSW and I am trying to get it to work in in Angular, but it isn't as straight-forward (or perhaps I am just dumb).

In **Vue**, I could ensure, that I `await` the service worker to start before proceeding.
```ts
async function startWorkers(): Promise<void> {
  if (process.env.NODE_ENV) {
    await repositoryWorker.start();
  }
}

startWorkers().then(() => {
  const app = createApp(App).use(router).use(store).use(vuetify).mount("#app");
});
```

In **Angular** (13), I cannot easily switch to using top-level awaits and I do not know whether I should. I currently ended up using `setTimeout`, which I'd rather not, but I do not know how else to accomplish this.

In https://github.com/mswjs/examples/tree/master/examples/rest-angular I'd love to have the `worker.start()` being awaited, because I currently did everything in the tutorial by @timdeschryver , but my requests did not go through.
Knowing the possible reason (I spent a few hours looking into it when I tried Vue a few weeks ago), I thought it might be, that the request is fired before the mock service worker has actually started (request is fired in `onInit` of a component).

The following helped, but I wonder if there is a prettier way without having to use `setTimeout`):

(`main.ts`)
```ts
if (environment.production) {
  enableProdMode();
} else {
  worker.start()
}

setTimeout(() => platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.error(err)), 100);
```

I'd also much more prefer to use the actual `environment(.*).ts` files for starting the worker, too.

Do you guys happen to have an idea of how to make this better? I just want to make sure the mock service worker is started before the first "request" is issued (or before the application even starts - whichever is easier) and if the mock service worker cannot be started for whatever reason, I wouldn't mind if the whole application doesn't start (in development mode obviously; production mode and its code shouldn't even know, that MSW exists).

**Comment by timdeschryver** [comment]
@divStar what about the following?
This should be similar to the vue snippet.
Personally, I've never experienced any problems with not awaiting `start` though.

```ts
worker.start().then(() => {
  platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.error(err)
})
```

**Comment by divStar** [comment]
Thank you - this will do. I just wish I wouldn't need to write something like:
```ts
if (environment.production) {
  enableProdMode();
  platformBrowserDynamic().bootstrapModule(AppModule).catch(err => console.error(err))
} else {
  worker.start().then(() =>
    platformBrowserDynamic().bootstrapModule(AppModule).catch(err => console.error(err)))
}
```
Extracting `platformBrowserDynamic().bootstrapModule(AppModule).catch(err => console.error(err))` to its own function helps in terms of readability, but I still need to call it in all of the branches of the if-statement.

I just wish MSW would have something like `worker.startSynchroneously()` or something :). Still, this works, so I am closing this and I apologize for the issue.
