### ISSUE TITLE
msw can't work in localhost or 127.0.0.1

### ISSUE THREAD

**Issue by yinsang** [mswjs/examples#84]
I tried **example/example/rest-react** ,while I opened http://localhost:3001 ,input sth, click submit button. Nothing happened .

expect: as http://10.0.0.6:3001. While click submit button, 
> John Maverick
> f79e82e8-c34a-4dc7-a49e-9fadc0979fda

 is shown.

**Comment by kettanaito** [comment]
Hey, @yinsang. Thanks for reporting this. I've just updated the entire examples suite, please take a look at the new examples. I'm quite certain they work on localhost without issues.
