### ISSUE TITLE
Question: Is it possible to intercept ALL requests?

### ISSUE THREAD

**Issue by onlywei** [mswjs/examples#95]
MSW seems to require me to write down a very specific URL in order to capture my request in Jest. I just want to set up a server to capture every request regardless of the URL and then. turn the server off after my tests are finished.

I've tried the following:

- `.get('*'`
- `.get(/.*/`
- `.get(/**`

None of these have worked.

**Comment by onlywei** [comment]
Hi @kettanaito. Thank you for the reply. I don't think that was my question though. I'm not worried about request _methods_. What I'm experiencing is that the wildcard "`*`" isn't capturing my request. I still get this:

>[MSW] Warning: captured a request without a matching request handler:

Even when I use `.all('*'`...

**Comment by kettanaito** [comment]
@onlywei, I mentioned methods because request interception is method _first_, path _second_. 

If there are still requests that don't match `http.all()`, I highly recommend following the [Debugging runbook](https://mswjs.io/docs/runbook). Let me know how far you get there.
